import React from 'react'

export default function head() {
  return (
    <React.Fragment>
      <title>Education | rineta.io</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="description" content="Generated by create next app" />
    </React.Fragment>
  )
}
